### PR TITLE
Adding Viva Goals Apis to graph explorer

### PR DESCRIPTION
**Pull request by ishatyagiit**

### CODE REVIEW

**Review by andrueastman — COMMENTED** [review]
Thanks for this @ishatyagiit 

Any chance you can fix the failing CI for the added sections? Ideally the `requestUrl` is expected to be full absolute URIs and not relative ones.

**Review by aboutdev — APPROVED** [review]

**Comment by ishatyagiit** [comment]
> Thanks for this @ishatyagiit
> 
> Any chance you can fix the failing CI for the added sections? Ideally the `requestUrl` is expected to be full absolute URIs and not relative ones.

Hi @andrueastman ,
Will update doc link once this PR is merged.
https://github.com/microsoftgraph/microsoft-graph-docs/pull/22967

Could you please help us in merging that?

**Comment by andrueastman** [comment]
Thanks for confirming. I've looped in the docs team to help out with the review and merge of the docs PR.

**Comment by ishatyagiit** [comment]
Hi @andrueastman ,
We are still waiting for another PR to get merged.
https://github.com/microsoftgraph/microsoft-graph-docs/pull/22967

Wanted to check how much time will this PR take once I update the doc link?

**Comment by andrueastman** [comment]
@ishatyagiit Once the links are fixed, I should be able to merge this in for you as soon as I confirm the CI validation checks are passing.

**Comment by ishatyagiit** [comment]
@andrueastman : Can we please check it now and merge ?

**Review by andrueastman — APPROVED** [review]

**Comment by ishatyagiit** [comment]
@andrueastman : When can we see these in graph explorer?

**Pull request merged**
