### PR TITLE
Add new required permission to Microsoft Graph Search API

### PR DESCRIPTION
**Pull request by yiwenwang-ms**

### CODE REVIEW

**Comment by irvinesunday** [comment]
Hi @yiwenwang-ms, we do not edit the permissions files directly through this process. We receive the files (v1.0 and beta) from a different team that scraps the permissions from the Microsoft Graph docs and hands them over to us to update here. If your permissions are in docs then they will eventually get here, since we update the files frequently (at least once a week). If it's already in the docs and you can't see it in GE, you can let us know so that we request for an updated file and update it here for it to reflect in GE.

**Comment by yiwenwang-ms** [comment]
Hi @irvinesunday, thanks for taking your time to review the PR. Have one question if you able to answer, do you have any sample for where I can add these permission in docs repo? I think you are saying https://github.com/microsoftgraph/microsoft-graph-docs. But still not find a suitable place to replace it.

**Comment by irvinesunday** [comment]
@millicentachieng are you able to point @yiwenwang-ms to where in the microsoft-graph-docs repo permissions can be updated?

**Comment by millicentachieng** [comment]
The permissions table in [this file](https://learn.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0) needs to be updated. Here's the link to the file on GitHub https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/search-query.md.

**Comment by yiwenwang-ms** [comment]
> The permissions table in [this file](https://learn.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0) needs to be updated.
> 
> Here's the link to the file on GitHub: https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/search-query.md.

Help a lot! Thank you very much!

**Pull request closed without merging**
