### PR TITLE
Add graph search interleaving sample to graph explorer

### PR DESCRIPTION
**Pull request by yiwenwang-ms**

### CODE REVIEW

**Review by thewahome — CHANGES_REQUESTED** [review]
Hey @yiwenwang-ms the documentation links changed to learn.microsoft.com from docs.microsoft.com . Can we have this change reflected?

**Comment by yiwenwang-ms** [comment]
> Hey @yiwenwang-ms the documentation links changed to learn.microsoft.com from docs.microsoft.com . Can we have this change reflected?

Hi @thewahome, I found all the documents link start with docs.microsoft.com, are you suggesting changing all the documentation link to learn.microsoft.com?

**Comment by thewahome** [comment]
No... just this that you are adding so that we change others incrementally

**Comment by yiwenwang-ms** [comment]
> 

Thank you, I updated all Search related doc links.

**Review by thewahome — APPROVED** [review]

**Comment by yiwenwang-ms** [comment]
Hi @thewahome, do you know whether there are any bugs in Graph Explorer, the merged sample query still not been showed up in Graph Explorer.

**Comment by thewahome** [comment]
@yiwenwang-ms it's not a bug. The work has to be merged to master for it to go live.

https://github.com/microsoftgraph/microsoft-graph-devx-content/pull/260

**Comment by yiwenwang-ms** [comment]
> @yiwenwang-ms it's not a bug. The work has to be merged to master for it to go live.
> 
> #260

Got it, thank you for merging!

**Comment by yiwenwang-ms** [comment]
> @yiwenwang-ms it's not a bug. The work has to be merged to master for it to go live.
> 
> #260

Got it, thanks for merging!

**Pull request merged**
