### PR TITLE
added group samples

### PR DESCRIPTION
**Pull request by sanana30**
added 6 groups samples

### CODE REVIEW

**Comment by irvinesunday** [comment]
@sanana30  let's add `postBody` properties to the POST samples.

**Comment by irvinesunday** [comment]
Also, in your efforts to resolve the json schema, you might have inadvertently left-indented the property and value schemas for all samples, hence why there is a huge diff. in your PR. Are you able to revert this and just specifically fix the schema for the affected samples - `Groups`?

**Comment by thewahome** [comment]
Please add `.vs` to the `.gitignore` file in the root of the project. It helps push only the necessary files to the repository

**Comment by sanana30** [comment]
@irvinesunday @thewahome - thanks for the suggestions. I made sure this time that the json schema was not left-indented this time, and I also added postBody properties. I hope this took care of all of the issues. I created the pull request in a new branch sn-groups here: https://github.com/microsoftgraph/microsoft-graph-devx-content/pull/88 

Thanks!

**Pull request closed without merging**
