### PR TITLE
Task: add tests

### PR DESCRIPTION
**Pull request by thewahome**
Adds tests to test basics like:
- whether the postBody is in the correct format
- sample queries exist in the file
- query has an id
- first word in the human name is lower cased 

Can be advanced to test other things like:
- sample GET  request queries running against the graph api respond with 2xx where it is expected
- query links provided open (or are not broken)
- permissions format / correctness

A GitHub actions workflow can be added to run the test after commits are made to a PR so that they can give accurate feedback to the user

### CODE REVIEW

**Comment by ddyett** [comment]
should be written in typescript for future supportability

**Comment by ddyett** [comment]
is the plan for this to be hooked into a pipeline so these are automatically run?

**Comment by thewahome** [comment]
> is the plan for this to be hooked into a pipeline so these are automatically run?

Yes. It can easily be connected to github actions

**Review by irvinesunday — COMMENTED** [review]
Let's add a further check on the `id` --> Should be unique within the list; and should be valid GUID

**Review by irvinesunday — APPROVED** [review]
We can add the id GUID validation check in a subsequent PR.

**Comment by ddyett** [comment]
please open an issue to make this typescript based.

**Pull request merged**
