### PR TITLE
Adding list devices and get device methods

### PR DESCRIPTION
**Pull request by hafowler**

### CODE REVIEW

**Comment by sanana30** [comment]
@bettirosengugi  hi Betti, can you please review this pull request?

CC: @irvinesunday @hafowler

**Review by irvinesunday — APPROVED** [review]
👍🏽

**Review by bettirosengugi — APPROVED** [review]

**Comment by bettirosengugi** [comment]
@hafowler please resolve the conflicts so we can merge this PR.
Thanks

**Comment by hafowler** [comment]
@bettirosengugi I believe I have resolved the conflicts. Please let me know if I have not.

**Pull request merged**
